### ISSUE TITLE
New update changed all saved worlds to "world"

### ISSUE THREAD

**Issue by jackah2** [harry0198/InfoHeads#11]
After updating to the newest version, all "world" values in `datastore.json` were changed to "world". This caused all of my infoheads to be wiped until manually fixing the json file.

**Comment by harry0198** [comment]
Hi, thanks for posting the issue! 

The latest update hasn't actually changed any of the serialiser logic which can be shown by the timestamps of the code on here. When this happens, it usually means that the world hasn't loaded yet. Maybe because you're using a different world manager or plugin was loaded externally e.g plugman. I can't unfortunately regulate this effectively as it's a weigh up between code integrity (should the plugin deserialise the infoheads - breaking the plugin if interacted with) or default to 'world'. And then whenever it actually gets saved to the json file, a file save was initiated for whatever reason that may be. 

But incase it wasn't one of those reasons, can you send the following:

- World Management Plugin(s) e.g Multiverse & version
- Plugin Management Plugin(s) e.g Plugman & version
- Server Version & Java version running
- Server software e.g Spigot

**Comment by jackah2** [comment]
You should add `load: POSTWORLD` to the plugin.yml to ensure the plugin loads after world management. We do however use Multiverse.

**Comment by harry0198** [comment]
Closing, cannot replicate
